### ISSUE TITLE
Weights file

### ISSUE THREAD

**Issue by qyzdao** [Ansire/sketch2normal#2]
I was wondering if you could give the trained weights file in the 'release'?

**Comment by Ansire** [comment]
sure

**Comment by qyzdao** [comment]
I have this bug when running --phase train or --phase test. Could you pls tell me how to solve it?

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 42, in main
    model.test(args)
  File "/home/0lineshader/sketch2normal/sketch2normal-checkpoint/NormalNet.py", line 316, in test
    test_images = [test_images[i:i+self.batch_size] for i in xrange(0, len(test_images), self.batch_size)]
NameError: name 'xrange' is not defined

**Comment by Ansire** [comment]
Maybe here is the solution: [https://stackoverflow.com/questions/17192158/nameerror-global-name-xrange-is-not-defined-in-python-3]
